### ISSUE TITLE
Torch not compiled with cuda

### ISSUE THREAD

**Issue by demonauthor** [devilismyfriend/ozen-toolkit#3]
I'm using Windows 11, and a fresh install of Miniconda 3. I cloned the repository for Ozen-toolkit and then ran the setup bat. It said everything was good to go, but when I drag my wav file onto the Drag_Here.cmd file, I get the following output. 

I also noted that running conda list -f pytorch in the Ozen environment shows no install of pytorch. What am I doing wrong here?

![Screen1](https://user-images.githubusercontent.com/65310261/227217092-3f1bc467-6099-4437-bc7f-252bf573d925.jpg)
![Screen2](https://user-images.githubusercontent.com/65310261/227217097-f0101d8f-dc0f-4e51-9e3d-22ee914461b5.jpg)

**Comment by demonauthor** [comment]
I think I fixed this by uninstalling the following that were installed with batch:  torch, torchaudio, torchvision... and then reinstalling them using this command within the ozen environment (it doesn't like the conda install for some reason:  
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

**Comment by AndrewBeniston** [comment]
Annoying, I'm having the exact same problem you've had, followed you back from DL-Art-School - but this doesn't fix my problem :(

**Comment by synkkedd** [comment]
Running this issue alongside, would love some help in-regards to this. I've tried literally everything at this point.
